experiment_name: ''

eval_on_test: True
num_epochs: 5000
batch_size: 2048
log_iterations: 100
patience: 80
optimizer_parameters:
  lr: 1.0e-4

# Paths to BERT
train_embeddings: 'data/embeddings/train_reduced.h5'
val_embeddings: 'data/embeddings/val_reduced.h5'
test_embeddings: 'data/embeddings/test_reduced.h5'

train_remapping: 'data/embeddings/train_remapped.fasta'
val_remapping: 'data/embeddings/val_remapped.fasta'
test_remapping: 'data/embeddings/test_remapped.fasta'

# Model parameters
model_type: 'FFN'
model_parameters:
  output_dim: 10
  hidden_dim: 32
  n_hidden_layers: 0
  dropout: 0.25
