output_files_name: 'inference_on_setHARD'

log_iterations: 100
n_draws: 1000
batch_size: 2
checkpoints_list:
  - trained_model_weights/LightAttention__702_16-04_23-00-52


embeddings: 'data_files/setHARD.h5'
remapping: 'data_files/setHARD.fasta'
key_format: fasta_descriptor



