experiment_name: 'ffn_bepler'

eval_on_test: True
num_epochs: 5000
batch_size: 2048
log_iterations: 100
patience: 80
optimizer_parameters:
  lr: 1.0e-4

# Paths to Data
train_embeddings: 'data/bepler_embeddings/train/embeddings/reduced_embeddings_file.h5'
val_embeddings: 'data/bepler_embeddings/val/embeddings/reduced_embeddings_file.h5'
test_embeddings: 'data/bepler_embeddings/deeploc_test/embeddings/reduced_embeddings_file.h5'

train_remapping: 'data/bepler_embeddings/train/remapped_sequences_file.fasta'
val_remapping: 'data/bepler_embeddings/val/remapped_sequences_file.fasta'
test_remapping: 'data/bepler_embeddings/deeploc_test/remapped_sequences_file.fasta'
key_format: hash

# Model parameters
model_type: 'FFN'
model_parameters:
  output_dim: 10
  hidden_dim: 32
  n_hidden_layers: 0
  dropout: 0.25
