output_files_name: 'inference_on_setHARD'

log_iterations: 100
n_draws: 1000
batch_size: 6
checkpoints_list:
  - runs/FFN_ffn_esm1b_17-09_09-31-52


embeddings: 'data/esm1b_embeddings/hard_test/embeddings/reduced_embeddings_file.h5'
remapping: 'data/esm1b_embeddings/hard_test/remapped_sequences_file.fasta'
key_format: hash



