experiment_name: 'T5Solubility'

num_epochs: 5000
batch_size: 150
log_iterations: 100
patience: 80
optimizer_parameters:
  lr: 5.0e-5


target: sol
unknown_solubility: False
loss_function: SolCrossEntropy


# Paths to Data
train_embeddings: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/train.h5'
train_remapping: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/train.fasta'
val_embeddings: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/val_homreduced.h5'
val_remapping: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/val_homreduced.fasta'
test_embeddings: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/test_as_per_deeploc.h5'
test_remapping: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/test_as_per_deeploc.fasta'
key_format: fasta_descriptor

# Model parameters
model_type: 'LightAttention'
model_parameters:
  dropout: 0.25
  kernel_size: 9
  output_dim: 2
